### ISSUE TITLE
4 Player Game End Condition? - Game rule clarification

### ISSUE THREAD

**Issue by ph-saya** [tally38/qwirkle-game#3]
While playing in a 4-player lobby, what are the game end conditions?

- Game ends after first player exhausts their hand
- Game ends after all but one player exhausts their hand
- Game ends after each player takes a turn after exhausting their hand

**Comment by tally38** [comment]
Game ends when first player exhausts there hand! The first player to exhaust their hand gets 6 bonus points!

**Comment by tally38** [comment]
I fixed a bug in the end-game logic in ab412d62d65fc030468d5e38ebff2d06eeb5dc10.
